### PR TITLE
ESA and IBRA regions

### PR DESCRIPTION
**Pull request by steve9164**
Fixes TerriaJS/terriajs#2191.

Before merging:
- [ ] Decide on suitable aliases for ESA, IBRA regions and IBRA subregions
- [x] Update vector tile server links to make vector-tiles-2016-12-05 the production vt server
- [x] Change URLs in regionMapping to reflect link changes

### CODE REVIEW

**Comment by steve9164** [comment]
Currently, for testing purposes, the IBRA regions have aliases:
- ibra7
- ibra7_name
- ibra7_sub
- ibra7_sub_name

I'm not sure what the csv column aliases should be for ibra7 regions and subregions.

**Comment by kring** [comment]
@tobybellwood you're probably the best person to answer Steve's question about column aliases.

**Comment by tobybellwood** [comment]
Yup - will do!

**Comment by steve9164** [comment]
@tobybellwood The regions are available here for now: http://nationalmap-regionmapping-test.terria.io/

Here are some test csvs: 
[csvs.zip](https://github.com/TerriaJS/nationalmap/files/665070/csvs.

**Comment by tobybellwood** [comment]
Thanks - I've passed it to the project for their comments.  I'll endeavour to put an IBRA7 region/subregion CSV onto data.gov.au to include it in the catalog/National Datasets

**Comment by tobybellwood** [comment]
How does this work?

Example | Current | Proposed Column Name | Column Alias
--------|---------|----------------------|-------------
Tanami | ibra7_name | ibra7_reg_name
TAN | ibra7 | ibra7_reg_code | ibra7_reg
Tanami Desert | ibra7_sub_name | ibra7_sub_name	
TAN01 | ibra7_sub | ibra7_sub_code | ibra7_sub

**Comment by steve9164** [comment]
I've updated the aliases, pushed the update to http://nationalmap-regionmapping-test.terria.io/ and also added the test csvs to a catalog on that site.

**Comment by kring** [comment]
Merging this, but let us know if you have any other comments @tobybellwood.

**Comment by tobybellwood** [comment]
Nope - I'm happy!

**Pull request merged**
